package test.model;

public class T_Ip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.ip_id
     *
     * @mbggenerated
     */
    private Integer ipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.ip_name
     *
     * @mbggenerated
     */
    private String ipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.ip_pid
     *
     * @mbggenerated
     */
    private Integer ipPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.ip_pname
     *
     * @mbggenerated
     */
    private String ipPname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.ip_ispid
     *
     * @mbggenerated
     */
    private String ipIspid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.server_disk_id
     *
     * @mbggenerated
     */
    private Integer serverDiskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.ip_network_operator
     *
     * @mbggenerated
     */
    private String ipNetworkOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ip.ip_remark
     *
     * @mbggenerated
     */
    private String ipRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.ip_id
     *
     * @return the value of t_ip.ip_id
     *
     * @mbggenerated
     */
    public Integer getIpId() {
        return ipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.ip_id
     *
     * @param ipId the value for t_ip.ip_id
     *
     * @mbggenerated
     */
    public void setIpId(Integer ipId) {
        this.ipId = ipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.ip_name
     *
     * @return the value of t_ip.ip_name
     *
     * @mbggenerated
     */
    public String getIpName() {
        return ipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.ip_name
     *
     * @param ipName the value for t_ip.ip_name
     *
     * @mbggenerated
     */
    public void setIpName(String ipName) {
        this.ipName = ipName == null ? null : ipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.ip_pid
     *
     * @return the value of t_ip.ip_pid
     *
     * @mbggenerated
     */
    public Integer getIpPid() {
        return ipPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.ip_pid
     *
     * @param ipPid the value for t_ip.ip_pid
     *
     * @mbggenerated
     */
    public void setIpPid(Integer ipPid) {
        this.ipPid = ipPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.ip_pname
     *
     * @return the value of t_ip.ip_pname
     *
     * @mbggenerated
     */
    public String getIpPname() {
        return ipPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.ip_pname
     *
     * @param ipPname the value for t_ip.ip_pname
     *
     * @mbggenerated
     */
    public void setIpPname(String ipPname) {
        this.ipPname = ipPname == null ? null : ipPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.ip_ispid
     *
     * @return the value of t_ip.ip_ispid
     *
     * @mbggenerated
     */
    public String getIpIspid() {
        return ipIspid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.ip_ispid
     *
     * @param ipIspid the value for t_ip.ip_ispid
     *
     * @mbggenerated
     */
    public void setIpIspid(String ipIspid) {
        this.ipIspid = ipIspid == null ? null : ipIspid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.server_disk_id
     *
     * @return the value of t_ip.server_disk_id
     *
     * @mbggenerated
     */
    public Integer getServerDiskId() {
        return serverDiskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.server_disk_id
     *
     * @param serverDiskId the value for t_ip.server_disk_id
     *
     * @mbggenerated
     */
    public void setServerDiskId(Integer serverDiskId) {
        this.serverDiskId = serverDiskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.ip_network_operator
     *
     * @return the value of t_ip.ip_network_operator
     *
     * @mbggenerated
     */
    public String getIpNetworkOperator() {
        return ipNetworkOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.ip_network_operator
     *
     * @param ipNetworkOperator the value for t_ip.ip_network_operator
     *
     * @mbggenerated
     */
    public void setIpNetworkOperator(String ipNetworkOperator) {
        this.ipNetworkOperator = ipNetworkOperator == null ? null : ipNetworkOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ip.ip_remark
     *
     * @return the value of t_ip.ip_remark
     *
     * @mbggenerated
     */
    public String getIpRemark() {
        return ipRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ip.ip_remark
     *
     * @param ipRemark the value for t_ip.ip_remark
     *
     * @mbggenerated
     */
    public void setIpRemark(String ipRemark) {
        this.ipRemark = ipRemark == null ? null : ipRemark.trim();
    }
}