package test.model;

import java.util.ArrayList;
import java.util.List;

public class T_IpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public T_IpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIpIdIsNull() {
            addCriterion("ip_id is null");
            return (Criteria) this;
        }

        public Criteria andIpIdIsNotNull() {
            addCriterion("ip_id is not null");
            return (Criteria) this;
        }

        public Criteria andIpIdEqualTo(Integer value) {
            addCriterion("ip_id =", value, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdNotEqualTo(Integer value) {
            addCriterion("ip_id <>", value, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdGreaterThan(Integer value) {
            addCriterion("ip_id >", value, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ip_id >=", value, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdLessThan(Integer value) {
            addCriterion("ip_id <", value, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdLessThanOrEqualTo(Integer value) {
            addCriterion("ip_id <=", value, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdIn(List<Integer> values) {
            addCriterion("ip_id in", values, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdNotIn(List<Integer> values) {
            addCriterion("ip_id not in", values, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdBetween(Integer value1, Integer value2) {
            addCriterion("ip_id between", value1, value2, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ip_id not between", value1, value2, "ipId");
            return (Criteria) this;
        }

        public Criteria andIpNameIsNull() {
            addCriterion("ip_name is null");
            return (Criteria) this;
        }

        public Criteria andIpNameIsNotNull() {
            addCriterion("ip_name is not null");
            return (Criteria) this;
        }

        public Criteria andIpNameEqualTo(String value) {
            addCriterion("ip_name =", value, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameNotEqualTo(String value) {
            addCriterion("ip_name <>", value, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameGreaterThan(String value) {
            addCriterion("ip_name >", value, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameGreaterThanOrEqualTo(String value) {
            addCriterion("ip_name >=", value, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameLessThan(String value) {
            addCriterion("ip_name <", value, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameLessThanOrEqualTo(String value) {
            addCriterion("ip_name <=", value, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameLike(String value) {
            addCriterion("ip_name like", value, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameNotLike(String value) {
            addCriterion("ip_name not like", value, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameIn(List<String> values) {
            addCriterion("ip_name in", values, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameNotIn(List<String> values) {
            addCriterion("ip_name not in", values, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameBetween(String value1, String value2) {
            addCriterion("ip_name between", value1, value2, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpNameNotBetween(String value1, String value2) {
            addCriterion("ip_name not between", value1, value2, "ipName");
            return (Criteria) this;
        }

        public Criteria andIpPidIsNull() {
            addCriterion("ip_pid is null");
            return (Criteria) this;
        }

        public Criteria andIpPidIsNotNull() {
            addCriterion("ip_pid is not null");
            return (Criteria) this;
        }

        public Criteria andIpPidEqualTo(Integer value) {
            addCriterion("ip_pid =", value, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidNotEqualTo(Integer value) {
            addCriterion("ip_pid <>", value, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidGreaterThan(Integer value) {
            addCriterion("ip_pid >", value, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ip_pid >=", value, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidLessThan(Integer value) {
            addCriterion("ip_pid <", value, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidLessThanOrEqualTo(Integer value) {
            addCriterion("ip_pid <=", value, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidIn(List<Integer> values) {
            addCriterion("ip_pid in", values, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidNotIn(List<Integer> values) {
            addCriterion("ip_pid not in", values, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidBetween(Integer value1, Integer value2) {
            addCriterion("ip_pid between", value1, value2, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPidNotBetween(Integer value1, Integer value2) {
            addCriterion("ip_pid not between", value1, value2, "ipPid");
            return (Criteria) this;
        }

        public Criteria andIpPnameIsNull() {
            addCriterion("ip_pname is null");
            return (Criteria) this;
        }

        public Criteria andIpPnameIsNotNull() {
            addCriterion("ip_pname is not null");
            return (Criteria) this;
        }

        public Criteria andIpPnameEqualTo(String value) {
            addCriterion("ip_pname =", value, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameNotEqualTo(String value) {
            addCriterion("ip_pname <>", value, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameGreaterThan(String value) {
            addCriterion("ip_pname >", value, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameGreaterThanOrEqualTo(String value) {
            addCriterion("ip_pname >=", value, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameLessThan(String value) {
            addCriterion("ip_pname <", value, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameLessThanOrEqualTo(String value) {
            addCriterion("ip_pname <=", value, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameLike(String value) {
            addCriterion("ip_pname like", value, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameNotLike(String value) {
            addCriterion("ip_pname not like", value, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameIn(List<String> values) {
            addCriterion("ip_pname in", values, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameNotIn(List<String> values) {
            addCriterion("ip_pname not in", values, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameBetween(String value1, String value2) {
            addCriterion("ip_pname between", value1, value2, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpPnameNotBetween(String value1, String value2) {
            addCriterion("ip_pname not between", value1, value2, "ipPname");
            return (Criteria) this;
        }

        public Criteria andIpIspidIsNull() {
            addCriterion("ip_ispid is null");
            return (Criteria) this;
        }

        public Criteria andIpIspidIsNotNull() {
            addCriterion("ip_ispid is not null");
            return (Criteria) this;
        }

        public Criteria andIpIspidEqualTo(String value) {
            addCriterion("ip_ispid =", value, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidNotEqualTo(String value) {
            addCriterion("ip_ispid <>", value, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidGreaterThan(String value) {
            addCriterion("ip_ispid >", value, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidGreaterThanOrEqualTo(String value) {
            addCriterion("ip_ispid >=", value, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidLessThan(String value) {
            addCriterion("ip_ispid <", value, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidLessThanOrEqualTo(String value) {
            addCriterion("ip_ispid <=", value, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidLike(String value) {
            addCriterion("ip_ispid like", value, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidNotLike(String value) {
            addCriterion("ip_ispid not like", value, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidIn(List<String> values) {
            addCriterion("ip_ispid in", values, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidNotIn(List<String> values) {
            addCriterion("ip_ispid not in", values, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidBetween(String value1, String value2) {
            addCriterion("ip_ispid between", value1, value2, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andIpIspidNotBetween(String value1, String value2) {
            addCriterion("ip_ispid not between", value1, value2, "ipIspid");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdIsNull() {
            addCriterion("server_disk_id is null");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdIsNotNull() {
            addCriterion("server_disk_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdEqualTo(Integer value) {
            addCriterion("server_disk_id =", value, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdNotEqualTo(Integer value) {
            addCriterion("server_disk_id <>", value, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdGreaterThan(Integer value) {
            addCriterion("server_disk_id >", value, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_disk_id >=", value, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdLessThan(Integer value) {
            addCriterion("server_disk_id <", value, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdLessThanOrEqualTo(Integer value) {
            addCriterion("server_disk_id <=", value, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdIn(List<Integer> values) {
            addCriterion("server_disk_id in", values, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdNotIn(List<Integer> values) {
            addCriterion("server_disk_id not in", values, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdBetween(Integer value1, Integer value2) {
            addCriterion("server_disk_id between", value1, value2, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andServerDiskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("server_disk_id not between", value1, value2, "serverDiskId");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorIsNull() {
            addCriterion("ip_network_operator is null");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorIsNotNull() {
            addCriterion("ip_network_operator is not null");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorEqualTo(String value) {
            addCriterion("ip_network_operator =", value, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorNotEqualTo(String value) {
            addCriterion("ip_network_operator <>", value, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorGreaterThan(String value) {
            addCriterion("ip_network_operator >", value, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("ip_network_operator >=", value, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorLessThan(String value) {
            addCriterion("ip_network_operator <", value, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorLessThanOrEqualTo(String value) {
            addCriterion("ip_network_operator <=", value, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorLike(String value) {
            addCriterion("ip_network_operator like", value, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorNotLike(String value) {
            addCriterion("ip_network_operator not like", value, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorIn(List<String> values) {
            addCriterion("ip_network_operator in", values, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorNotIn(List<String> values) {
            addCriterion("ip_network_operator not in", values, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorBetween(String value1, String value2) {
            addCriterion("ip_network_operator between", value1, value2, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpNetworkOperatorNotBetween(String value1, String value2) {
            addCriterion("ip_network_operator not between", value1, value2, "ipNetworkOperator");
            return (Criteria) this;
        }

        public Criteria andIpRemarkIsNull() {
            addCriterion("ip_remark is null");
            return (Criteria) this;
        }

        public Criteria andIpRemarkIsNotNull() {
            addCriterion("ip_remark is not null");
            return (Criteria) this;
        }

        public Criteria andIpRemarkEqualTo(String value) {
            addCriterion("ip_remark =", value, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkNotEqualTo(String value) {
            addCriterion("ip_remark <>", value, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkGreaterThan(String value) {
            addCriterion("ip_remark >", value, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("ip_remark >=", value, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkLessThan(String value) {
            addCriterion("ip_remark <", value, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkLessThanOrEqualTo(String value) {
            addCriterion("ip_remark <=", value, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkLike(String value) {
            addCriterion("ip_remark like", value, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkNotLike(String value) {
            addCriterion("ip_remark not like", value, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkIn(List<String> values) {
            addCriterion("ip_remark in", values, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkNotIn(List<String> values) {
            addCriterion("ip_remark not in", values, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkBetween(String value1, String value2) {
            addCriterion("ip_remark between", value1, value2, "ipRemark");
            return (Criteria) this;
        }

        public Criteria andIpRemarkNotBetween(String value1, String value2) {
            addCriterion("ip_remark not between", value1, value2, "ipRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ip
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}