package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.T_Ip;
import test.model.T_IpExample;

public interface T_IpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int countByExample(T_IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int deleteByExample(T_IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int insert(T_Ip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int insertSelective(T_Ip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    List<T_Ip> selectByExample(T_IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    T_Ip selectByPrimaryKey(Integer ipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") T_Ip record, @Param("example") T_IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") T_Ip record, @Param("example") T_IpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(T_Ip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ip
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(T_Ip record);
}